# Generated by Django 5.0.1 on 2024-01-13 22:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks_app', '0004_alter_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='room_name',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 1, 13, 22, 19, 3, 980108))]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room_id')},
        ),
    ]
