# Generated by Django 5.0.1 on 2024-01-13 22:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks_app', '0005_rename_id_reservation_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='id_of_the_room',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='room_name',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 1, 13, 22, 20, 55, 433645))]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'id_of_the_room')},
        ),
    ]
