# Generated by Django 5.0.1 on 2024-01-13 22:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks_app', '0006_rename_room_id_reservation_id_of_the_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id_of_the_room',
            new_name='id',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 1, 13, 22, 38, 5, 439307))]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'id')},
        ),
    ]
