# Generated by Django 5.0.1 on 2024-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks_app', '0007_rename_id_of_the_room_reservation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='room_id',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room_id')},
        ),
    ]
